# Generated by Django 4.1.5 on 2023-01-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapply',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
