# Generated by Django 4.1.5 on 2023-01-24 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_alter_course_instructor'),
        ('course_apply', '0002_alter_courseapply_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseapply',
            unique_together={('course', 'student')},
        ),
    ]
