# Generated by Django 4.1.5 on 2023-01-24 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_course_name'),
        ('course_apply', '0003_alter_courseapply_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseapply',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='courseapply',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentOf', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseapply',
            unique_together={('course', 'student', 'status')},
        ),
    ]
