# Generated by Django 4.1.5 on 2023-01-24 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_course_name'),
        ('course_apply', '0004_alter_courseapply_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseapply',
            unique_together={('course', 'student', 'status')},
        ),
    ]
