# Generated by Django 4.1.5 on 2023-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
