# Generated by Django 4.1.5 on 2023-01-18 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='faculty_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_advisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
