# Generated by Django 4.1.5 on 2023-01-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otplogin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdetails',
            name='link_string',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otpdetails',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='otpdetails',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
