# Generated by Django 4.1.5 on 2023-01-14 06:28

from django.db import migrations
import usercustom.manager


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objectsall', usercustom.manager.UserManager()),
                ('objects', usercustom.manager.UserManagerfiltered()),
            ],
        ),
    ]
