# Generated by Django 4.1.5 on 2023-01-18 05:48

from django.db import migrations
import usercustom.manager


class Migration(migrations.Migration):

    dependencies = [
        ('usercustom', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', usercustom.manager.UserManager()),
                ('objectsall', usercustom.manager.UserManagerfiltered()),
            ],
        ),
    ]
