import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../../components/Navbar'
import Table from '../../components/Table'
import { useState, useEffect } from 'react'
import AdvisorTable from '../../components/AdvisorTable'
import {GetCoursesAdvisor} from "../../helpers/AdvisorFunctions"

// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  //Student and course and credits and instructor dummy json object create
  // const PendingcourseList = [
  //   {
  //     id: 1,
  //     studentname: "John", 
  //     instructor: 'John',
  //     course: 'Math',
  //     credit: 3,
      
  //   },
  //   {
  //     id: 2,
  //     studentname: "asf", 
  //     instructor: 'Jane',
  //     course: 'English',
  //     credit: 3
  //   },
  //   {
  //     id: 3,
  //     studentname: "test",  
  //     instructor: 'Jack',
  //     course: 'Science',

  //     credit: 3
  //   },
  // ]
  const [PendingcourseList, setPendingcourseList] = useState([])
  useEffect(() => {
    const fetchCourses = async () => {
      alert("enter useeffect")
      // alert(PendingcourseList[0])
      const courses = await GetCoursesAdvisor()
      setPendingcourseList(courses)
      console.log(PendingcourseList)
    }
    fetchCourses()
  }, [])
  return (
    <>
      <Head>
        <title>Advisor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* <Navbar />
        <div>
          <p> Student </p>
        </div> */}
        <h1 className="text-center">Welcome To Advisor Page</h1>
        <br></br>
        <br></br>

        <div className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
            <AdvisorTable courseList={PendingcourseList} />
        </div>
        
      </main>
    </>
  )
}
