import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/Navbar";
import Table from "../../components/Table";
import { useState, useEffect } from "react";
import AdvisorTable from "../../components/AdvisorTable";
import { GetCoursesAdvisor } from "../../helpers/AdvisorFunctions";

import { AuthContext } from "@/context/AuthContext";
import { useContext } from "react";

export default function Home() {
    // auth context
    const { user, isLoggedIn, logout } = useContext(AuthContext);

    if (!isLoggedIn) {
        return <div>Not logged in</div>;
    }
    console.log(user.groups);
    if (user.groups[0] !== "Faculty Advisor") {
        return <div>Not an Advisor</div>;
    }



    const [PendingcourseList, setPendingcourseList] = useState([]);

    useEffect(() => {
        const fetchCourses = async () => {
            const courses = await GetCoursesAdvisor();
            setPendingcourseList(courses);
            // console.log(PendingcourseList);
        };
        fetchCourses();
    }, []);
    return (
        <>
            <Head>
                <title>Advisor</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main>
                {/* <Navbar />
        <div>
          <p> Student </p>
        </div> */}
                <h1 className="text-center">Welcome user {user.username}</h1>
                <h1 className="text-center">Email: {user.email}</h1>
                <br></br>
                <br></br>

                <div className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
                    <AdvisorTable courseList={PendingcourseList} />
                </div>
            </main>
        </>
    );
}
