import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../../components/Navbar'
import { useState, useEffect } from 'react'
import { useRef } from 'react'

// import Table from '../../components/Table'
import InstructorTable from 'components/InstructorTable'
import {AddCourseInstructor,DeleteCourseInstructor,GetCoursesInstructor} from 'helpers/InstructorFunctions'
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // const courseList = [
  //   {
  //     id: 1,
  //     course_name: 'Math',
  //     student: 'John',
  //     credit: 3
  //   },
  //   {
  //     id: 1,
  //     course_name: 'Science',
  //     student: 'Alex',
  //     credit: 3
  //   },
  //   {
  //     id: 1,
  //     course_name: 'English',
  //     student: 'Felix',
  //     credit: 3
  //   },
  // ]
  const [courseList, setCourseList] = useState([])


  useEffect(() => {
    const fetchCourses = async () => {
      const courses = await GetCoursesInstructor()
      setCourseList(courses)
    }
    fetchCourses()
  }, [])
  
  const addCourseName = useRef()
  const addCourseCredits = useRef()
  return (
    <>
      <Head>
        <title>Instructor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {/* <Navbar />
        <div>
          <p> Student </p>
        </div> */}
        <h1 className="text-center">Welcome To Instructor Page</h1>
        <br></br>
        <br></br>

        <div className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
          <InstructorTable courseList={courseList} />
          {/* form for adding course */}
          <br></br>
          <br></br>

          <h1 className="text-center font-bold" >Add Course</h1>
          <br></br>
          <form >
            <div className="mb-6 ">
              <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Course Name</label>
              <input  ref={addCourseName} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 blockw-40 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="CS302" required />
            </div>
            <div className="mb-6">
              <label htmlFor="password" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Credits</label>
              <input ref={addCourseCredits}type="number"  className="w-40 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" required />
            </div>
            <button type="submit" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-40 sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" onClick={()=>{AddCourseInstructor(addCourseName.current.value,addCourseCredits.current.value)}}>ADD</button>
          </form>
          {/*Add heading for form */}
        </div>

        {/* <h1 className="text-center">Delete Course</h1>
        <br></br>
        <form >
          <div className="mb-6 ">
            <label className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Course Name</label>
            <input  ref={deleteCourseName} className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-40 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="CS302" required />
          </div>
          <button type="submit" className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-40 sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" onClick={DeleteCourseInstructor()}>DELETE</button>
        </form> */}

      </main>
    </>
  )
}
