import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/Navbar";
import Table from "../../components/Table";
import { useState, useEffect } from "react";

import { AuthContext } from "@/context/AuthContext";
import { useContext } from "react";

import SelectMenu from "components/SelectMenu";
import StudentTable from "components/StudentTable";
import { GetCoursesStudent, AllCoursesStudent, ApplyCourseStudent } from "helpers/StudentFunctions";

export default function Home() {
    // auth context
    const { user, isLoggedIn, logout, loading } = useContext(AuthContext);

    const [courseList, setCourseList] = useState([]);
    const [allCourses, setAllCourses] = useState([]);
    const [pageLoading, setPageLoading] = useState(true);
    const fetchCourses = async () => {
        setPageLoading(true);
        console.log("Student.js: fetchCourses: ");
        const courses = await GetCoursesStudent();
        const allCourses = await AllCoursesStudent();

        setAllCourses(allCourses);
        setCourseList(courses);
        setPageLoading(false);
    };
    useEffect(() => {
        fetchCourses();
        console.log(
            "Student.js: useEffect: courseList: ",
        )
    }, []);

    if (!isLoggedIn) {
        return <div>Not logged in</div>;
    }

    if (user.groups[0] !== "Student") {
        return <div>Not a Student</div>;
    }

    if (loading || pageLoading) {
        return <div>Loading...</div>;
    }

    return (
        <>
            <Head>
                <title>Student</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <main>
                <h1 className="text-center">Welcome {user.username}</h1>
                <h1 className="text-center">Your email is {user.email}</h1>
                <br></br>
                <br></br>

                <div className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
                    <StudentTable courseList={courseList} />
                    <br></br>
                    <br></br>

                    <SelectMenu
                        Heading="Select a Course"
                        courseList={allCourses}
                        fetchCourses={fetchCourses}
                    />
                    {/*Add heading for form */}
                </div>
            </main>
        </>
    );
}
