import Head from "next/head";
import Image from "next/image";
import Navbar from "../../components/Navbar";
import Table from "../../components/Table";
import { useState } from "react";
import { useRef } from "react";
import Router from "next/router";
// import { localStorage } from 'next/localstorage';

// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })
// make a global varaible to be accessed in every file


export default function Home() {
    // make email ref
    const otpRef = useRef();
    // set error message
    const [errorMessage, setErrorMessage] = useState("");

    const handleClick = async(e) => {
        e.preventDefault();
        setErrorMessage("");
        const otp = otpRef.current.value;
        console.log(otp);

        // send otp to backend
        const data =await fetch("http://localhost:8000/verify", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ "otp":otp ,"email":"2020csb1142@iitrpr.ac.in"}),
        });
        const res =await data.json();
        // if success, redirect to student page
        console.log(res)
        console.log(res.access)
        console.log(res.login)
        if (res.login) {
            // set token in local storage
            localStorage.setItem("token", res.access);
            console.log("success");
            // Router.push("/student");
        }
        // if error, show error message
        else {
            console.log("error");
            setErrorMessage("Something went wrong");
        }
    };
    return (
        <>
            <Head>
                <title>Student</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
                    rel="stylesheet"
                    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
                    crossorigin="anonymous"
                ></link>
                <script
                    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
                    crossorigin="anonymous"
                    defer
                ></script>
            </Head>
            <main className="container">
                {/* bootstarp taoast and error */}
                {errorMessage && (
                    <div className="alert alert-danger" role="alert">
                        {errorMessage}
                    </div>
                )}

                <div className="mb-3">
                    <label htmlFor="exampleInputEmail1" className="form-label">
                        Enter OTP
                    </label>
                    <input
                        type="text"
                        className="form-control"
                        id="exampleInputEmail1"
                        aria-describedby="emailHelp"
                        ref={otpRef}
                    />
                </div>
                <button
                    type="button"
                    class="btn text-red"
                    onClick={handleClick}
                >
                    Submit
                </button>
            </main>
        </>
    );
}
